version: "3.8"

services:
  app:
    depends_on:
      - audit
      - redis
    build:
      context: .
      target: prod
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - SERVER__HOST=0.0.0.0
      - REDIS__PORT=6379
      - REDIS__HOST=redis
    ports:
      - "${SERVER__PORT}:${SERVER__PORT}"
    init: true

  audit:
    build:
      context: .
      target: audit

  redis:
    image: redis:7.0-alpine3.16
    restart: always
    volumes:
      - redis-data:/data
    ports:
      - "${REDIS__PORT}:6379"

  redis-commander:
    depends_on:
      - redis
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"

volumes:
  redis-data:
